ALTER TABLE paper_trades
  ADD COLUMN IF NOT EXISTS entry_price DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS exit_price DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS status TEXT CHECK (status IN ('OPEN','CLOSED')) DEFAULT 'OPEN',
  ADD COLUMN IF NOT EXISTS trail_top DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS tp_pct DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS sl_pct DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS trail_pct DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS risk_pct DOUBLE PRECISION;
