version: '3.9'
services:
  prometheus:
    image: prom/prometheus
    command: ['--config.file=/etc/prometheus/prometheus.yml']
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alerts.yml:/etc/prometheus/alerts.yml
    ports:
      - '9090:9090'
  alertmanager:
    image: prom/alertmanager
    ports:
      - '9093:9093'
    environment:
      - ALERT_WEBHOOK_URL=${ALERT_WEBHOOK_URL:-}
  grafana:
    image: grafana/grafana
    ports:
      - '3001:3000'
    depends_on:
      - prometheus
