groups:
- name: smoke
  rules:
  - alert: AlwaysFiring
    expr: vector(1)
    for: 0m
    labels:
      severity: warning
    annotations:
      summary: "Smoke test — this should appear in Alertmanager"
