global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - /etc/prometheus/rules/*.yml
  - /etc/prometheus/rules/*.yaml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: loki
    static_configs:
      - targets: ['loki:3100']

  - job_name: api
    metrics_path: /metrics
    static_configs:
      - targets: ['deploy-api:3000']

  - job_name: otel-collector
    static_configs:
      - targets: ['otel-collector:8888']
