global:
  scrape_interval: 15s
rule_files:
  - /etc/prometheus/alerts.yml
  - /etc/prometheus/recording-rules.yml
  - /etc/prometheus/alerts-burnrate.yml
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: api
    metrics_path: /metrics
    static_configs:
      - targets: ["deploy-api:3000"]
  - job_name: otel-collector
    static_configs:
      - targets: ['otel-collector:8888']
  - job_name: loki
    static_configs:
      - targets: ['loki:3100']
