groups:
- name: api-latency
  rules:
  - record: route:http_request_duration_seconds:p95
    expr: histogram_quantile(
        0.95,
        sum by (le,route) (
          rate(http_request_duration_seconds_bucket{job="api",route!="/metrics"}[30m])
        )
      )
