name: CI
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - name: Install
        run: npm ci
      - name: Lint
        run: npm run lint || true
      - name: Tests
        run: npm test
      - name: Build
        run: npm run build || true
      - name: Docker build
        run: docker build -t crypto-signals:test .
